# Generated by Django 4.2.7 on 2026-06-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Larami Holiday Hotel', max_length=255)),
                ('address', models.TextField(default='No 10 Chief Chung Street, Aleto Eleme, Rivers State')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('manager_whatsapp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('STANDARD', 'Standard Room - ₦25,000/night'), ('DELUXE', 'Deluxe Room - ₦35,000/night'), ('EXECUTIVE', 'Executive Room - ₦45,000/night'), ('SUITE', 'Suite - ₦60,000/night'), ('STUDIO', 'Studio - ₦20,000/night')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('capacity', models.IntegerField(default=2)),
                ('amenities', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.hotel')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
