# Generated by Django 4.2.7 on 2026-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True),
        ),
    ]
